[package]
name = "core"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
iced = { workspace = true }
slotmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
directories = { workspace = true }
reqwest = { workspace = true }
mime_guess = { workspace = true }
strum = { workspace = true }
regex = { workspace = true }
hcl-rs = { workspace = true }
similar = { workspace = true }
